### ISSUE TITLE
LVGL for scanline generation

### ISSUE THREAD

**Issue by barbiani** [raspberrypi/pico-playground#29]
Hi,

Since I've learned that this project does not use a full framebuffer I recalled the [LVGL](https://lvgl.io/) project, that does the same for low ram microcontrollers.

Do you think that the pico would be fast enough to render the lines on demand?

Thank you.

**Comment by JamesH65** [comment]
The Doom port renders scanlines on the fly, also the Slint project has a Pico port that renders on the fly. https://slint-ui.com/blog/porting-slint-to-microcontrollers.html
