### ISSUE TITLE
Sprite composition in ram, from flash.

### ISSUE THREAD

**Issue by barbiani** [raspberrypi/pico-playground#31]
Hello everybody,

I'd like to make a screen with a bunch of sprites that are a combination of simpler images.

The base images would be stored in flash and composed into ram on demand. The display would work from RAM then...

I understand that the packed images might be rle encoded and some work will be needed to compose them if this code is not already there somewhere else in the project.

What do you think?

Thank you.

**Comment by JamesH65** [comment]
Probably best to ask this sort of question on the forums, more people there who will be able to give an answer, perhaps even people who have already done it.

forums.raspberrypi.com
