### ISSUE TITLE
VGA Connection Pinout in the scanvideo/ directory seems incorrect

### ISSUE THREAD

**Issue by NybuTG** [raspberrypi/pico-playground#38]
![image](https://user-images.githubusercontent.com/62597368/212380245-c8c61b74-f00f-4c13-b536-2810a3a7a0c8.png)

As can be seen, some of the resistors used for colors are connected to a ground instead of a GP# pin

![image](https://user-images.githubusercontent.com/62597368/212380669-d63ac1bc-db00-46f9-a3c6-d4220c7f564a.png)
It appears the correct pinout can be taken from the Raspberry Pi "VGA Carrier Board" schematic

**Comment by lurch** [comment]
Duplicate of #20 ?

**Comment by NybuTG** [comment]
Duplicate
