### ISSUE TITLE
Screenshots for video?

### ISSUE THREAD

**Issue by drudru** [raspberrypi/pico-playground#4]
It would be great to have some screenshots for the video demos. Other demos might benefit as well.

**Comment by kilograham** [comment]
good idea

**Comment by lurch** [comment]
As long as a screenshot of `sprite_demo` doesn't scare the children :wink:

**Comment by BambooEngineer** [comment]
![IMG_20210330_214357238](https://user-images.githubusercontent.com/37255295/113311230-16054480-92d7-11eb-8d66-1ea6de94443e.jpg)

This is the color pattern i get, i dont think its my Resistor DACs but i could be wrong. The raspberry demo1 example looks fine for me but the floating heads has a black and blue box moving in the middle of the screen !

**Comment by kilograham** [comment]
you probably forgot that there is a 1 pin gap between red and green

**Comment by kilograham** [comment]
also i added some screenshots

**Comment by BambooEngineer** [comment]
THANK YOU ! It worked
