### ISSUE TITLE
Where is "scanvideo.h" file?

### ISSUE THREAD

**Issue by siriokds** [raspberrypi/pico-playground#7]

**Comment by lurch** [comment]
https://github.com/raspberrypi/pico-extras/blob/master/src/rp2_common/pico_scanvideo_dpi/include/pico/scanvideo.h

**Comment by siriokds** [comment]
> https://github.com/raspberrypi/pico-extras/blob/master/src/rp2_common/pico_scanvideo_dpi/include/pico/scanvideo.h

Thank you.
