### ISSUE TITLE
8080 and 6800 parallel bus example

### ISSUE THREAD

**Issue by siriokds** [raspberrypi/pico-playground#8]
On Rp2040 Datasheet page 324,
I can read: "The programmable input/output block (PIO) is a versatile hardware interface. It can support a variety of IO standards, including:  8080 and 6800 parallel bus..."

Is there an example about 8080 parallel bus ?
Tnx

**Comment by lurch** [comment]
> Is there an example about 8080 parallel bus ?

Not yet, but we might add one when we're less busy with more-critical stuff!

This issue is closely related to https://github.com/raspberrypi/pico-examples/issues/48 ?

**Comment by siriokds** [comment]
Yes. Thank you for your quick answer.

**Comment by 3s1d** [comment]
Hi,

did anything change in the past 1.5 years? I am about to start development on my 8080 based display and an example would really help me a lot (especially as this is my first time pio'ing something).

Thanks.

**Comment by fu709691151** [comment]
Do you have any examples?
